spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/Verwee
    username: postgres
    password: 1853
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    properties:
      hibernate:
        format_sql: true
logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type: TRACE
      springframework:
        jdbc:
          core: DEBUG
        data:
          jpa:
            repository: DEBUG